### ISSUE TITLE
Planning to Write a Blog Article About this Package

### ISSUE THREAD

**Issue by dhurlburtusa** [ghengeveld/react-async#11]
Hello Gert,

About a month or two ago, I needed the functionality `react-async` provides. I looked at `react-loadable` and many others, but I like `react-async` much better and works the way I was thinking about implementing my own. Thanks for beating me to it!

I like how it is promise-centric. It matches closely with the terminology found at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Syntax. 

So, I am one of the authors at https://alligator.io/. Would you like to provide some feedback before I write the article? For example, are there any highlights I should point out?

I was planning on demonstrating various uses of `react-async`, one of which shows how it can be used with `react-lazily-render`, another using `https://github.com/afuggini/loadscript`.

**Comment by ghengeveld** [comment]
Hey, thanks for the feedback! Indeed I modelled it to match the Promise terminology. As you probably know there is a `Pending` component but it does something slightly different: render while deferFn has not been run yet. I've been struggling with the naming here, because I had the same concern. I finally settled on deviating from the Promise spec because `Loading` and `Pending` are probably more intuitive (if you're not thinking of the Promise spec) in the literal sense of the word. The alternative would be `Pending` (for `isLoading`) and `Waiting` (for `!run`). Other suggestions are welcome.

As for the article, I'm really excited to read how others see and use it. I think you already found the main highlight: working with promises. Other highlights are the rationale (keeping state locally), its flexibility (soon even as a hook) and the promise that it will leverage new React features when they arrive, without breaking changes (it will wrap around Suspense under the hood).
