### ISSUE TITLE
Add `onFulfill` and Alias `onResolve`

### ISSUE THREAD

**Issue by dhurlburtusa** [ghengeveld/react-async#39]
Since v6.x is using the Promise spec terminology, I think we should add `onFulfill` callback to take the place of `onResolve`. Since v6.x has already been released, `onResolve` can be an alias or fallback if `onFulfill` is not present. Or both callbacks could be called if present.

Thoughts?

**Comment by ghengeveld** [comment]
Technically, `resolve` and `reject` are the names of the [Promise executor callbacks](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), so I think `onResolve` makes sense. This is exactly what confused me most about the Promise spec. A promise can *resolve* with either a value, causing it to become fulfilled, or with another Promise, causing it to continue executing that Promise.

Needless to say, in this case `onResolve` will always fulfill, because we don't pass it a Promise.

**Comment by dhurlburtusa** [comment]
Okay. That makes sense. Resolving is the action that takes the promise to the fulfilled state. It could resolve to a synchronous value or to an asynchronous value via a new Promise which will eventually get fulfilled with a synchronous value. And likewise, rejecting is the action that takes the promise to the rejected state.

As I was responding, I thought of something and I'd like to throw it out as another suggestion. You probably have already thought of it and I am not sure if there is a strong need or desire for it but I wonder if an `onStatusChange` or `onStateChange` callback would be useful. It can go along with the new status API. I can open another issue if specific to it if you want and maybe gather feedback from the community.

Thanks again for the well-thought out library.

(I hope you are not getting tired of all the suggestions from the community.)

**Comment by ghengeveld** [comment]
I haven't considered a state change callback yet, but I have considered adopting the [state reducer pattern](https://kentcdodds.com/blog/the-state-reducer-pattern-with-react-hooks). Let's open a new issue to discuss if this makes sense.

I'm really happy with the feedback I'm getting now. Sure I've thought about many of these things but it never hurts to reconsider or look at things from another angle. Going back and forth a couple times helps iron out the rough edges. The whole `status` thing actually originated from a colleague who wanted state-specific types in TypeScript in order to avoid optional types. I never felt the need for it myself because I'm not using TypeScript in my current projects. 

Please keep the feedback coming.

**Comment by dhurlburtusa** [comment]
Closing since the reasoning behind name choice is very sound.
