### ISSUE TITLE
Default headers with useFetch

### ISSUE THREAD

**Issue by Ericnr** [ghengeveld/react-async#56]
Is there a way to set default headers with useFetch, or do I have to use something like axios + useAsync for that?

**Comment by ghengeveld** [comment]
If you mean configuring them once and then using `useFetch` without specifying them each time, then no, there isn't a way. However you can just keep those headers in a file somewhere and pass it to each instance of `useFetch`:

```js
import { useFetch } from "react-async"
import { apiHeaders } from "../config"

const MyComponent = () => {
  const headers = { ...apiHeaders, Accept: "application/json" }
  const { data, isLoading } = useFetch("/api/example", { headers })
}
```

In my opinion this is better than preconfiguring it globally, because it's much more explicit. Less magic is better than reducing code, because it keeps your code simple and understandable.

**Comment by Ericnr** [comment]
Cool, I'll close the issue.
