### ISSUE TITLE
Incorrest state when testing with renderHook

### ISSUE THREAD

**Issue by kostrse** [ghengeveld/react-async#81]
I was trying to test behavior of the useAsync hook using the renderHook from the testing-library/react-hooks, and found the following issues (which is probably I'm trying to use the library in a wrong way).

First, when hook returns it's initial state, it returns initialValue (as expected), but it also indicates that the promise has been already resolved:

```ts
it('should set into proper initial state', async () => {
    const asyncFunc = () => Promise.resolve(2);

    const { result } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);
    expect(result.current.isResolved).toBe(false); // FAILS, ALREADY RESOLVED
});
```

I expected it to be either `{ data: 1, isResolved: false }`, or `{ data: 2, isResolved: true }`.

Second issue, is that for some reason the waitForNextUpdate never resolve:

```ts
it('should resolve resolved promise', async () => {
    // already resolved
    const asyncFunc = () => Promise.resolve(2);

    const { result, waitForNextUpdate } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);

    await waitForNextUpdate(); // NEVER RESOLVE
});

it('should resolve asynchronous promise', async () => {
    // will resolve in 50ms
    const asyncFunc = () => new Promise(resolve => setTimeout(resolve, 50)).then(() => 2);

    const { result, waitForNextUpdate } = renderHook(() => useAsync(asyncFunc, { initialValue: 1 }));

    expect(result.current.value).toEqual(1);

    await waitForNextUpdate(); // NEVER RESOLVE
});
```

This is probably related to the first issue - promise is in resolved state already but the value from the promise wasn't set.

**Comment by kostrse** [comment]
Posted by mistake to testing-library/react-hooks-testing-library/issues/148.

**Comment by mpeyper** [comment]
Author of `@testing-library/react-hooks` here....

`waitForNextUpdate` resolves the next time the component renders, so if it's never resolving, it suggests nothing is triggering a render.

I'm not ruling out the issue bring in `renderHook`, so I'm happy to help track down the issue.

**Comment by ghengeveld** [comment]
Sorry this took so long, and thanks for reporting.

Your first issue is with [the way the `status` is determined](https://github.com/ghengeveld/react-async/blob/f5dda65f4dd8fc60357dd3d86474e1f10f222737/packages/react-async/src/status.js#L10) when passing an `initialValue`. It's specified to be `fulfilled` when an `initialValue` is provided. It works this way because that allows us to render the UI with the initial data, as if it's already fulfilled. Otherwise you'd be presented a loading indicator (`<IfPending>`) rather than something useful. Changing this would be a really big change which I'm not inclined to do. We can however update the docs to be more clear about this behavior.

Your second issue is with `promiseFn` not being triggered when `initialValue` is specified. It may seem like a bug with `waitForNextUpdate`, but in fact @mpeyper is correct: there is nothing triggering a rerender in this case. The reason is that [`promiseFn` is never invoked](https://github.com/ghengeveld/react-async/blob/f5dda65f4dd8fc60357dd3d86474e1f10f222737/packages/react-async/src/useAsync.js#L88-L97) when it's already "pre-initialized", so it also will never resolve. In this scenario React Async will simply take the `initialValue` and stop to wait until something changes. The reason it works this way is to avoid unnecessary data fetching when you already have fetched the data (which you passed in as `initialValue`). If you want to trigger the `promiseFn`, you can either call `reload()` or set a `watch` / `watchFn`.

In general, it's best practice to test hooks by testing a component that uses it. This is [how we test `useAsync` and `useFetch`](https://github.com/ghengeveld/react-async/blob/f5dda65f4dd8fc60357dd3d86474e1f10f222737/packages/react-async/src/useAsync.spec.js#L30-L32). Regardless, I wouldn't expect things to break when using `react-hooks-testing-library`. Although I'm not familiar with it, it should work as advertised.

By the way, you don't need to test React Async's inner workings, it's already tested thoroughly. You should however test the way it integrates with your app, of course.

I'm going to take this as a reminder that React Async's behavior when passed an `initialValue` should be better documented. Right now the [documentation on `initialValue`](https://github.com/ghengeveld/react-async/blob/master/README.md#initialvalue) is pretty sparse.

**Comment by ghengeveld** [comment]
If you still think one of these issues warrants a further discussion, please explain the use case where React Async's current behavior doesn't work. Then we can consider making a change to fit that use case, without changing the default behavior.

**Comment by ghengeveld** [comment]
I've added some [clarification on `initialValue`](https://github.com/ghengeveld/react-async/blob/next/README.md#initialvalue) to the docs. Closing this issue now. Feel free to reopen if you have a certain use case where this behavior does not work.
